[package]
authors = ["Alan Hoffmeister <alanhoffmeister@gmail.com>"]
name = "rust-endless-jumper"
version = "0.1.0"

[dependencies]
rand = "0.3.15"

[dependencies.sdl2]
default-features = false
features = ["ttf", "image", "gfx", "mixer"]
version = "0.29.1"
